[platformio]
default_envs = Upload_UPDI

[env]
platform = atmelmegaavr
framework = arduino

; Target chip
board = ATtiny1616

; Clock: 5 MHz
board_build.f_cpu = 5000000L
board_hardware.oscillator = internal

; Brown-out detection (recommended for Li-ion)
board_hardware.bod = 2.7v

; Keep EEPROM through uploads
board_hardware.eesave = yes

; Leave UPDI pin as UPDI
board_hardware.rstpin = updi

; Serial monitor (if you use SoftwareSerial USART)
monitor_speed = 9600


; -------------------------------------------------------
; Upload using SerialUPDI (USB-serial + 4.7k resistor)
; -------------------------------------------------------
[env:Upload_UPDI]
upload_protocol = serialupdi

; Use your COM port here (or omit to auto-detect)
; upload_port = COM5

; SerialUPDI runs reliably at 115200
upload_speed = 115200

upload_flags =

